### ISSUE TITLE
Bad file name in GC Dataset Annotations

### ISSUE THREAD

**Issue by amiryanj** [ShanghaiTechCVDL/CIDNN#3]
There is a file named (007427 橾怮怮婓笢栝膘耟揭 渭賸竭壅 羶獗堤懂.txt) that makes the create_dataset.py fail.

**Comment by Binbose** [comment]
Easy fix by just deleting the chinese letters.
I would be interested what it means though :D

**Comment by piaozhx** [comment]
I think @Binbose is right. Actually, I don't know what it means, either. It comes from original dataset.

**Comment by junjun520416** [comment]
这篇文章是论文的复现吗？是官方的还是按照论文思想自己写的？
